# This workflow looks for changes to Flock patches within Nest, and then
# creates or updates a parallel PR in the Flock repository.
#
# Flock patches live in the Nest repository so that Flock's history can be
# rebased and reconstituted automatically.
#
# Nest accumulates changes to Flutter in the form of patch files. These patch
# files are played on top of Flutter to create a version called Flock. Reviewing
# patch files in isolation is counterproductive, because developers can't see
# any of the code around the changes. This workflow takes the patches in the
# Nest repository, plays them on top of Flutter, and then generates a linked
# PR in the Flock repository that shows the actual differences caused by the
# new patches.
#
# If a PR is submitted to Nest without any changes to patches, then this
# workflow aborts.
#
# After this workflow runs, go to github.com/join-the-flock/flock and locate
# the new PR with the Flutter diff. Review the changes there. When satisfied
# with the changes, close the PR in Flock, and merge the PR in Nest.
#
# The PR that's generated in the Flock repository is created on behalf of
# whichever user submitted the PR that ran this workflow.

on:
  pull_request:
    # This workflow handles new Nest PRs, as well as PR changes, and re-opened PRs.
    types: [opened, synchronize, reopened]
    branches:
      - main

# Update these variables to fit your custom fork configuration.
env:
  # The GitHub location of your Flutter fork.
  FLOCK_REPO: "join-the-flock/flock"

  # A Personal Access Token (PAT) so that this action can create and force-push PRs.
  GITHUB_PAT: ${{ secrets.REPO_WORKFLOW_PAT }}

  # The Flutter branch that the patches apply to.
  FLUTTER_BRANCH: "master"

name: create-and-update-flock-pr-from-nest-patch
permissions:
  contents: write

jobs:
  create-and-update-flock-pr-from-nest-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Nest
        uses: actions/checkout@v4
        with:
          path: 'nest'
          fetch-depth: 0 # Checkout everything to get access to the tags
          repository: ${{github.repository}}
          ref: ${{github.event.pull_request.head.ref}}
          token: ${{ env.GITHUB_PAT }}

      - name: Look for Flock patch changes
        run: |
          cd nest
          git fetch origin ${{ github.base_ref }}
          if git diff --quiet origin/${{ github.base_ref }}...HEAD -- patches/; then
            echo "No changes to Flock patches. Exiting workflow."
            echo "has_patch_changes=false" >> $GITHUB_ENV
          else
            echo "This PR includes Flock patch changes. Creating Flock PR for review."
            echo "has_patch_changes=true" >> $GITHUB_ENV
          fi

      - name: Checkout Flock
        if: env.has_patch_changes == 'true'
        uses: actions/checkout@v4
        with:
          path: 'nest/flock'
          fetch-depth: 0 # Checkout everything to get access to the tags
          repository: ${{ env.FLOCK_REPO }}
          ref: ${{ env.FLUTTER_BRANCH }}
          token: ${{ env.GITHUB_PAT }}

      - name: Create branch for Flock PR
        if: env.has_patch_changes == 'true'
        working-directory: nest/flock
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

          git checkout -b ${{github.event.pull_request.head.ref}}

      - name: Setup Python
        if: env.has_patch_changes == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Apply Nest patches to Flock
        if: env.has_patch_changes == 'true'
        run: |
          echo "Apply patches..."
          cd nest
          python -u tools/git-import-patches.py patches

      - name: Push Flock changes to Flock repo for PR
        if: env.has_patch_changes == 'true'
        working-directory: nest/flock
        run: |
          # Store the PAT in a file that can be accessed by the
          # GitHub CLI.
          echo "$GITHUB_PAT" > token.txt

          # Authorize GitHub CLI for the current repository and
          # create a pull-requests containing the updates.
          gh auth login --with-token < token.txt

          echo "Working directory: `pwd`"
          echo "Git remote:"
          echo `git remote -v`
          echo "Looking for branch: ${{github.event.pull_request.head.ref}}"
          echo "PR list search:"
          list_output=$(gh pr list --state open --base ${{ env.FLUTTER_BRANCH }} --head ${{github.event.pull_request.head.ref}} --repo ${{ env.FLOCK_REPO }})
          echo "$list_output"
          echo "----"

          pr_exists=$(gh pr list \
            --state open \
            --base ${{ env.FLUTTER_BRANCH }} \
            --head ${{github.event.pull_request.head.ref}} \
            --repo ${{ env.FLOCK_REPO }} \
            --json number \
            --jq '.[0].number'\
          )

          # If a PR exists, inform the user. Otherwise, create a new PR.
          if [ -n "$pr_exists" ]; then
            # Force push to the existing PR branch.
            git push -f origin ${{github.event.pull_request.head.ref}}

            echo "Flock PR already exists, and it was updated with a force push."
          else
            echo "Flock PR doesn't exist yet. Creating it."

            # Save the PR description to a file so that we can insert newlines.
            echo -e "${{ github.event.pull_request.body }}\n\n---\n\nThis Flock PR is derived from the patch in the following Nest PR: \n${{ github.event.pull_request.url }}" > pr_description.txt

            # Create the PR.
            echo "Creating a PR..."
            gh pr create \
              --title "${{ github.event.pull_request.title }}" \
              --body-file "pr_description.txt" \
              --head ${{ github.event.pull_request.head.ref }} \
              --base ${{ env.FLUTTER_BRANCH }}
          fi
